# github workflow to build project and create new release

name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: write-all

concurrency:
  group: 'deploy'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Set up pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: |
          pnpm install
          pnpm install:web

      - name: Deploy Web
        run: |
          pnpm deploy:web
          tar -czvf api.tar.gz api

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/DerTyp7214/HomeApi:latest .
          docker push ghcr.io/DerTyp7214/HomeApi:latest

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api

      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Upload Assets
        id: upload_assets
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.package-version.outputs.current-version }}
          title: ${{ steps.package-version.outputs.current-version }}
          prerelease: false
          files: |
            api.tar.gz
